IF
	AreaCheck("BG1001")
	Global("JO_GLOBAL_IWD_BG2","GLOBAL",1)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@1057)
		Wait(7)
		CreateVisualEffectObject("PORTALH",Myself)
		Wait(1)
		DestroySelf()
		Continue()
END

IF
    Global("JO_GLOBAL_IN_IWD1","GLOBAL",1)
    Global("JO_GLOBAL_IN_IWD2","GLOBAL",1)
	OR(2)
		Global("FC_GLOBAL_IWD_VARIABLE","GLOBAL",12)
		Global("FC_GLOBAL_IWD_VARIABLE","GLOBAL",6)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@1057)
		Wait(7)
		CreateVisualEffectObject("PORTALH",Myself)
		Wait(1)
		DestroySelf()
		Continue()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("FC_GLOBAL_IWD_VARIABLE","GLOBAL",-1)
		ApplySpell(Myself,DRYAD_TELEPORT)
END

IF
	Global("Set_SavedLoc","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("Set_SavedLoc","LOCALS",1)
		SaveObjectLocation("LOCALS","SavedLoc",Myself)
		Continue()
END

IF
	OR(3)
		NumTimesTalkedTo(0)
		Global("FC_GLOBAL_IWD_VARIABLE","GLOBAL",5)
		Global("FC_GLOBAL_IWD_VARIABLE","GLOBAL",11)
	See(Player1)
	Range(LastSeenBy(Myself),10)
THEN
	RESPONSE #100
		FaceObject(LastSeenBy(Myself))
		SmallWait(5)
		StartDialogNoSet(LastSeenBy(Myself))
END

IF
	ActionListEmpty()
	!NearSavedLocation(Myself,"LOCALSSavedLoc",5)
THEN
	RESPONSE #100
		MoveToSavedLocation("SavedLoc","LOCALS")
END









