IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FadeToColor([0.0],0)
		Wait(1)
		ActionOverride(Player2,LeaveAreaLUA("AR0406","",[987.1358],SWW))
		ActionOverride(Player3,LeaveAreaLUA("AR0406","",[1037.1395],NW))
		ActionOverride(Player4,LeaveAreaLUA("AR0406","",[972.1316],N))
		ActionOverride(Player5,LeaveAreaLUA("AR0406","",[1080.1401],NNE))
		ActionOverride(Player6,LeaveAreaLUA("AR0406","",[1046.1407],SE))
		LeaveAreaLUAPanic("AR0406","",[1010.1383],S)
		LeaveAreaLUA("AR0406","",[1010.1383],S)
		SetGlobal("PARTY_IN_ICEWIND_DALE","GLOBAL",0)
		Wait(1)
		//SetSequence(SEQ_SLEEP)
		//ActionOverride(Player2,SetSequence(SEQ_SLEEP))
		//ActionOverride(Player3,SetSequence(SEQ_SLEEP))
		//ActionOverride(Player4,SetSequence(SEQ_SLEEP))
		//ActionOverride(Player5,SetSequence(SEQ_SLEEP))
		//ActionOverride(Player6,SetSequence(SEQ_SLEEP))
		SmallWait(5)
		Rest()
		ActionOverride(Player2,Rest())
		ActionOverride(Player3,Rest())
		ActionOverride(Player4,Rest())
		ActionOverride(Player5,Rest())
		ActionOverride(Player6,Rest())
		Wait(1)
		FadeFromColor([15.0],0)
		CreateVisualEffectObject("PORTALH",Player1)
		CreateVisualEffectObject("PORTALH",Player2)
		CreateVisualEffectObject("PORTALH",Player3)
		CreateVisualEffectObject("PORTALH",Player4)
		CreateVisualEffectObject("PORTALH",Player5)
		CreateVisualEffectObject("PORTALH",Player6)
		Wait(2)
		//SetSequence(SEQ_AWAKE)
		//ActionOverride(Player2,SetSequence(SEQ_AWAKE))
		//ActionOverride(Player3,SetSequence(SEQ_AWAKE))
		//ActionOverride(Player4,SetSequence(SEQ_AWAKE))
		//ActionOverride(Player5,SetSequence(SEQ_AWAKE))
		//ActionOverride(Player6,SetSequence(SEQ_AWAKE))
		//Wait(1)
		SetGlobal("MOVING_TO_IWD","GLOBAL",6)
		SetGlobal("FC_GLOBAL_IWD_VARIABLE","GLOBAL",11)
		EndCutSceneMode()
END

























